-- ==========================================
-- HUMAN-FRIENDLY TICKET NUMBERS
-- ==========================================
-- Adds tickets.ticket_number, a short sequential number the UI shows as
-- "TKT-0042" in place of the UUID. Nothing else changes: tickets.id stays
-- the primary key, every foreign key and API keeps using it, and "Copy ID"
-- in the UI still copies the UUID.
--
-- No backend code change is needed: the JPA Ticket entity doesn't map this
-- column, so Hibernate leaves it out of its INSERT and the identity default
-- fills it in (ddl-auto=update only ever adds columns, never drops them).
--
-- Numbers are unique and increasing but not gapless - a rolled-back insert
-- burns a number, which is fine for a reference customers quote.
--
-- Apply BEFORE deploying the frontend: /api/tickets selects this column by
-- name, and PostgREST rejects a select naming a column that doesn't exist.
-- Safe to re-run. Runs as one transaction, so a ticket can't be inserted
-- half-way through and miss its number.

BEGIN;

ALTER TABLE public.tickets ADD COLUMN IF NOT EXISTS ticket_number BIGINT;

-- Number existing tickets oldest-first, so the backfilled references read in
-- the order tickets actually arrived. Offsetting by the current max keeps a
-- re-run from colliding with numbers already handed out.
WITH numbered AS (
    SELECT id,
           (SELECT COALESCE(max(ticket_number), 0) FROM public.tickets)
             + row_number() OVER (ORDER BY created_at NULLS FIRST, id) AS n
    FROM public.tickets
    WHERE ticket_number IS NULL
)
UPDATE public.tickets t
SET ticket_number = numbered.n
FROM numbered
WHERE t.id = numbered.id;

-- An identity column must be NOT NULL before it can be made an identity.
ALTER TABLE public.tickets ALTER COLUMN ticket_number SET NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_attribute
        WHERE attrelid = 'public.tickets'::regclass
          AND attname = 'ticket_number'
          AND attidentity <> ''
    ) THEN
        -- BY DEFAULT (not ALWAYS) so a restore or the backfill above can still
        -- write explicit values.
        ALTER TABLE public.tickets ALTER COLUMN ticket_number ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;
END $$;

-- Start new tickets after the highest backfilled number (or at 1 on an empty table).
SELECT setval(
    pg_get_serial_sequence('public.tickets', 'ticket_number'),
    GREATEST((SELECT max(ticket_number) FROM public.tickets), 1),
    (SELECT max(ticket_number) FROM public.tickets) IS NOT NULL
);

-- Enforces uniqueness and serves "find ticket TKT-0042" lookups.
CREATE UNIQUE INDEX IF NOT EXISTS tickets_ticket_number_key ON public.tickets (ticket_number);

COMMIT;
